/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libqsplegacy_jni_QSPLegacyLib */

#ifndef _Included_com_libqsplegacy_jni_QSPLegacyLib
#define _Included_com_libqsplegacy_jni_QSPLegacyLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_init
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_terminate
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    enableDebugMode
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_enableDebugMode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getCurStateData
 * Signature: ()Lcom/libqsplegacy/jni/QSPLegacyLib/ExecutionState;
 */
JNIEXPORT jobject JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getCurStateData
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getFullRefreshCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getFullRefreshCount
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getQstFullPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getQstFullPath
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getCurLoc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getCurLoc
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getExprValue
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getExprValue
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getCompiledDateTime
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getCompiledDateTime
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getMainDesc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getMainDesc
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    isMainDescChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_isMainDescChanged
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getVarsDesc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getVarsDesc
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    isVarsDescChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_isVarsDescChanged
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getVarValuesCount
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getVarValuesCount
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getVarValues
 * Signature: (Ljava/lang/String;I)Lcom/libqsplegacy/jni/QSPLegacyLib/VarValResp;
 */
JNIEXPORT jobject JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getVarValues
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getMaxVarsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getMaxVarsCount
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getVarNameByIndex
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getVarNameByIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    setInputStrText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_setInputStrText
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getActions
 * Signature: ()[Lcom/libqsplegacy/jni/QSPLegacyLib/ListItem;
 */
JNIEXPORT jobjectArray JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getActions
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    isActionsChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_isActionsChanged
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    executeSelActionCode
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_executeSelActionCode
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getSelActionIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getSelActionIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    setSelActionIndex
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_setSelActionIndex
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getObjects
 * Signature: ()[Lcom/libqsplegacy/jni/QSPLegacyLib/ListItem;
 */
JNIEXPORT jobjectArray JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getObjects
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    isObjectsChanged
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_isObjectsChanged
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getSelObjectIndex
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getSelObjectIndex
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    setSelObjectIndex
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_setSelObjectIndex
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    execString
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_execString
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    execLocationCode
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_execLocationCode
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    execCounter
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_execCounter
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    execUserInput
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_execUserInput
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getLastErrorData
 * Signature: ()Lcom/libqsplegacy/jni/QSPLegacyLib/ErrorData;
 */
JNIEXPORT jobject JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getLastErrorData
  (JNIEnv *, jobject);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    getErrorDesc
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_getErrorDesc
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    restartGame
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_restartGame
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    loadGameWorldFromData
 * Signature: ([BLjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_loadGameWorldFromData
  (JNIEnv *, jobject, jbyteArray, jstring, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    loadGameWorldFromFD
 * Signature: (ILjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_loadGameWorldFromFD
  (JNIEnv *, jobject, jint, jstring, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    loadGameWorldFromPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_loadGameWorldFromPath
  (JNIEnv *, jobject, jstring, jstring, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    saveGameAsData
 * Signature: (Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_saveGameAsData
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    saveGameByFD
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_saveGameByFD
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    saveGameByPath
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_saveGameByPath
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    openSavedGameFromData
 * Signature: ([BZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_openSavedGameFromData
  (JNIEnv *, jobject, jbyteArray, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    openSavedGameFromFD
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_openSavedGameFromFD
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_libqsplegacy_jni_QSPLegacyLib
 * Method:    openSavedGameFromPath
 * Signature: (Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_libqsplegacy_jni_QSPLegacyLib_openSavedGameFromPath
  (JNIEnv *, jobject, jstring, jboolean);

#ifdef __cplusplus
}
#endif
#endif
